apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  serviceName: "neo4j"
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:4.4.39-community
          resources:
            limits:
              memory: 4Gi
              cpu: "200m"
            requests:
              memory: "600Mi"
              cpu: "100m"
          env:
            - name: NEO4J_AUTH
              value: neo4j/password
            - name: NEO4J_dbms_memory_heap_initial__size
              value: "512M"
            - name: NEO4J_dbms_memory_heap_max__size
              value: "256M"
            - name: NEO4J_dbms_default_listen_address
              value: "0.0.0.0"
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
          ports:
            - containerPort: 7687
              name: bolt
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
            - name: neo4j-logs
              mountPath: /logs
  volumeClaimTemplates:
    - metadata:
        name: neo4j-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: neo4j-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  clusterIP: None
  selector:
    app: neo4j
  ports:
    - port: 7687
      targetPort: 7687