spring.application.name: config-server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brijesh777/ecommerce-config-server
          username: brijesh777
          password: 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
          default-label: main


server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

